package program;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ndaru Pratiwi
 */
public class DashboardAdmin extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;

    /**
     * Creates new form DasboardAdmin
     */
    public DashboardAdmin(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnKonfirmasiTransaksi = new javax.swing.JButton();
        btnRaport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPPDB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DASHBOARD ADMIN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 60, 245, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("KONFIRMASI TRANSAKSI");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 140, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("INPUT  RAPORT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 140, 131, 30);

        btnKonfirmasiTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKonfirmasiTransaksi.setText("Konfirmasi Transaksi");
        btnKonfirmasiTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnKonfirmasiTransaksi);
        btnKonfirmasiTransaksi.setBounds(90, 190, 195, 31);

        btnRaport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRaport.setText("Raport");
        btnRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaportActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaport);
        btnRaport.setBounds(410, 190, 85, 31);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(470, 20, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("PPDB TK PELITA HARAPAN PG ASEMBAGUS  SITUBONDO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 270, 480, 22);

        btnPPDB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPPDB.setText("PPDB");
        btnPPDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnPPDB);
        btnPPDB.setBounds(250, 300, 110, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/C.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 623, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfirmasiTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiTransaksiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InputTransaksi(null, true).setVisible(true);
    }//GEN-LAST:event_btnKonfirmasiTransaksiActionPerformed

    private void btnRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaportActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InputRaport(null, true).setVisible(true);
    }//GEN-LAST:event_btnRaportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LogoutAdmin(null, true).setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPPDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPDBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PPDB(null, true).setVisible(true);
    }//GEN-LAST:event_btnPPDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DashboardAdmin dialog = new DashboardAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void
                            windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);

                    }

                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfirmasiTransaksi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPPDB;
    private javax.swing.JButton btnRaport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
