package program;

import program.DashboardAdmin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ndaru Pratiwi
 */
public class InputRaport extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;

    /**
     * Creates new form InputRaport
     */
    public InputRaport(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    private void hapuslayar() {
        txtNamaSiswa.setText("");
        txtNoInduk.setText("");
        txtKelas.setText("");
        txtGol.setText("");
        txtMoralAgama.setText("");
        txtKD.setText("");
        txtBahasa.setText("");
        txtSosialEmosional.setText("");

    }

    public static Connection getConnection() {
        Connection connection = null;
        String driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/raport"; //ganti dengan database mu
        String user = "root";
        String password = "";
        if (connection == null) {
            try {
                Class.forName(driver);
                connection = DriverManager.getConnection(url, user, password);
            } catch (ClassNotFoundException | SQLException error) {
                System.exit(0);
            }

        }
        return connection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoralAgama = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKD = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSosialEmosional = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBahasa = new javax.swing.JTextArea();
        btnInsert = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtNamaSiswa = new javax.swing.JTextField();
        txtNoInduk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKelas = new javax.swing.JTextField();
        btnDownload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("INPUT RAPORT TK PELITA HARAPAN PG ASEMBAGUS SITUBONDO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 10, 650, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Siswa :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 50, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nomor Induk :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 50, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nilai Moral dan Agama");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 140, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kemampuan Dasar");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 140, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bahasa");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 280, 60, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Sosial Emosional");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(500, 280, 110, 30);

        txtMoralAgama.setColumns(20);
        txtMoralAgama.setRows(5);
        jScrollPane1.setViewportView(txtMoralAgama);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(16, 180, 300, 96);

        txtKD.setColumns(20);
        txtKD.setRows(5);
        jScrollPane2.setViewportView(txtKD);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(390, 180, 310, 96);

        txtSosialEmosional.setColumns(20);
        txtSosialEmosional.setRows(5);
        jScrollPane3.setViewportView(txtSosialEmosional);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(390, 320, 310, 96);

        txtBahasa.setColumns(20);
        txtBahasa.setRows(5);
        jScrollPane4.setViewportView(txtBahasa);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(20, 320, 300, 96);

        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert);
        btnInsert.setBounds(350, 440, 80, 25);

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(590, 440, 73, 25);
        jPanel1.add(txtNamaSiswa);
        txtNamaSiswa.setBounds(170, 50, 200, 30);
        jPanel1.add(txtNoInduk);
        txtNoInduk.setBounds(520, 50, 170, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Golongan :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 90, 90, 30);
        jPanel1.add(txtGol);
        txtGol.setBounds(520, 90, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kelas :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 90, 80, 30);
        jPanel1.add(txtKelas);
        txtKelas.setBounds(170, 90, 200, 30);

        btnDownload.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDownload.setText("DOWNLOAD");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        jPanel1.add(btnDownload);
        btnDownload.setBounds(450, 440, 120, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/C.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNamaSiswa.getText().equals("") || txtNoInduk.getText().equals("") || txtKelas.getText().equals("") || txtGol.getText().equals("") || txtMoralAgama.getText().equals("") || txtKD.getText().equals("") || txtBahasa.getText().equals("") || txtSosialEmosional.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Data Tida Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                hapuslayar();
            } else {
                Class.forName("com.mysql.jdbc.Driver");

                con = DriverManager.getConnection("jdbc:mysql://localhost/raport", "root", "");
                st = con.createStatement();
                String simpan = "INSERT INTO raport VALUES('" + txtNamaSiswa.getText() + "','" + txtNoInduk.getText() + "' , '" + txtKelas.getText() + "', '" + txtGol.getText() + "', '" + txtMoralAgama.getText() + "','" + txtKD.getText() + "','" + txtBahasa.getText() + "','" + txtSosialEmosional.getText() + "')";
                st = con.createStatement();
                int SA = st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(null, "Input Data Raport Berhasil");
                hapuslayar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "This Account isAlready exist / Duplicate Account ", "Pesan", JOptionPane.WARNING_MESSAGE);
            hapuslayar();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardAdmin(null, true).setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportRaport.jasper"), null, FormRaport.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InputRaport dialog = new InputRaport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void
                            windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);

                    }

                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtBahasa;
    private javax.swing.JTextField txtGol;
    private javax.swing.JTextArea txtKD;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextArea txtMoralAgama;
    private javax.swing.JTextField txtNamaSiswa;
    private javax.swing.JTextField txtNoInduk;
    private javax.swing.JTextArea txtSosialEmosional;
    // End of variables declaration//GEN-END:variables
}
