package program;

import program.DashboardUser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ndaru Pratiwi
 */
public class Pendaftaran extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;

    /**
     * Creates new form Pendaftaran
     */
    public Pendaftaran(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    private void hapuslayar() {
        txtNama.setText("");
        txtTTL.setText("");
        cboJK.setSelectedIndex(0);
        txtAnakKe.setText("");
        cboAgama.setSelectedIndex(0);
        cboGolDar.setSelectedIndex(0);
        cboKewarganegaraan.setSelectedIndex(0);
        txtAlamat.setText("");
        txtAyah.setText("");
        txtIbu.setText("");
        txtPTO.setText("");
        txtPO.setText("");
        txtEmail.setText("");
        txtTelp.setText("");
        cboTransfer.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboJK = new javax.swing.JComboBox<>();
        cboAgama = new javax.swing.JComboBox<>();
        cboGolDar = new javax.swing.JComboBox<>();
        cboKewarganegaraan = new javax.swing.JComboBox<>();
        cboTransfer = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        txtTTL = new javax.swing.JTextField();
        txtAnakKe = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtAyah = new javax.swing.JTextField();
        txtIbu = new javax.swing.JTextField();
        txtPTO = new javax.swing.JTextField();
        txtPO = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnDaftar = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtTelp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FORM PENDAFTARAN SISWA BARU TK PELITA HARAPAN PG ASEMBAGUS SITUBONDO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 620, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 50, 50, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tempat, Tanggal Lahir :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 80, 140, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 110, 79, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Anak Ke-  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 140, 61, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Agama : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 160, 49, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Golongan Darah : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 190, 98, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Kewarganegaraan : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 220, 109, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Alamat : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 250, 49, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ayah : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 280, 39, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Ibu :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 310, 26, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Pendidikan Terakhir Ortu :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 340, 143, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Perkerjaan Ortu :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 370, 94, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Email :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 400, 35, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Telephone :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 430, 67, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Transfer Biaya Daftar Ulang :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 460, 170, 14);

        cboJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jPanel1.add(cboJK);
        cboJK.setBounds(210, 100, 90, 30);

        cboAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen ", "Katolik", "Hindu", "Budha", "Kong Hu Cu" }));
        jPanel1.add(cboAgama);
        cboAgama.setBounds(210, 160, 70, 30);

        cboGolDar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        jPanel1.add(cboGolDar);
        cboGolDar.setBounds(210, 190, 60, 30);

        cboKewarganegaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WNA", "WNI" }));
        jPanel1.add(cboKewarganegaraan);
        cboKewarganegaraan.setBounds(210, 220, 60, 30);

        cboTransfer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32270001000", "32270002000", "32270003000", "32270004000", "32270005000", " " }));
        jPanel1.add(cboTransfer);
        cboTransfer.setBounds(210, 460, 110, 30);
        jPanel1.add(txtNama);
        txtNama.setBounds(210, 40, 220, 30);
        jPanel1.add(txtTTL);
        txtTTL.setBounds(210, 70, 220, 30);
        jPanel1.add(txtAnakKe);
        txtAnakKe.setBounds(210, 130, 220, 30);
        jPanel1.add(txtAlamat);
        txtAlamat.setBounds(210, 250, 220, 30);
        jPanel1.add(txtAyah);
        txtAyah.setBounds(210, 280, 220, 30);
        jPanel1.add(txtIbu);
        txtIbu.setBounds(210, 310, 220, 30);
        jPanel1.add(txtPTO);
        txtPTO.setBounds(210, 340, 220, 30);
        jPanel1.add(txtPO);
        txtPO.setBounds(210, 370, 220, 30);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(210, 400, 220, 30);

        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftar);
        btnDaftar.setBounds(520, 60, 70, 30);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah);
        btnUbah.setBounds(520, 100, 70, 30);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(520, 140, 70, 30);

        btnBersih.setText("Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });
        jPanel1.add(btnBersih);
        btnBersih.setBounds(520, 180, 70, 30);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(520, 220, 70, 30);
        jPanel1.add(txtTelp);
        txtTelp.setBounds(210, 430, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/C.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-3, 0, 650, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNama.getText().equals("") || txtTTL.getText().equals("") || cboJK.getSelectedItem().equals("") || txtAnakKe.getText().equals("") || cboAgama.getSelectedItem().equals("") || cboGolDar.getSelectedItem().equals("") || cboKewarganegaraan.getSelectedItem().equals("") || txtAlamat.getText().equals("") || txtAyah.getText().equals("") || txtIbu.getText().equals("") || txtPTO.getText().equals("") || txtPO.getText().equals("") || txtEmail.getText().equals("") || txtTelp.getText().equals("") || cboTransfer.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(this, "Data Tida Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                hapuslayar();
            } else {
                Class.forName("com.mysql.jdbc.Driver");

                con = DriverManager.getConnection("jdbc:mysql://localhost/formppdb", "root", "");
                st = con.createStatement();
                String simpan = "INSERT INTO formppdb VALUES('" + txtNama.getText() + "','" + txtTTL.getText() + "' , '" + cboJK.getSelectedItem() + "', '" + txtAnakKe.getText() + "','" + cboAgama.getSelectedItem() + "', '" + cboGolDar.getSelectedItem() + "', '" + cboKewarganegaraan.getSelectedItem() + "', '" + txtAlamat.getText() + "','" + txtAyah.getText() + "','" + txtIbu.getText() + "','" + txtPTO.getText() + "','" + txtPO.getText() + "','" + txtEmail.getText() + "','" + txtTelp.getText() + "','" + cboTransfer.getSelectedItem() + "')";
                st = con.createStatement();
                int SA = st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(null, "Pendaftaran Peserta Didik Baru Berhasil");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "This Account isAlready exist / Duplicate Account ", "Pesan", JOptionPane.WARNING_MESSAGE);
            hapuslayar();
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/formppdb", "root", "");
            st = con.createStatement();
            String sql = "UPDATE formppdb SET TempatTanggalLahir='"+txtTTL.getText()+"',"+"JenisKelamin='"+cboJK.getSelectedItem()+"',"+"AnakKe-='"+txtAnakKe.getText()+"',"+"Agama='"+cboAgama.getSelectedItem()+"',"+"GolonganDarah='"+cboGolDar.getSelectedItem()+"',"+"Kewarganegaraan='"+cboKewarganegaraan.getSelectedItem()+"',"+"Alamat='"+txtAlamat.getText()+"',"+"Ayah='"+txtAyah.getText()+"',"+"Ibu='"+txtIbu.getText()+"',"+"PendidikanTerakhirOrtu='"+txtPTO.getText()+"',"+"PerkerjaanOrtu='"+txtPO.getText()+"',"+"Email='"+txtEmail.getText()+"',"+"Telephone='"+txtTelp.getText()+"',"+"TransferDaftarUlang='"+cboTransfer.getSelectedItem()+"'"+"WHERE Nama ='"+txtNama.getText()+ "'";
            int SA = st.executeUpdate(sql);
            if(SA == 1){
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            con.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Gagal");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/formppdb", "root", "");
            st = con.createStatement();
            String hapus = "DELETE FROM formppdb WHERE Nama ='" + txtNama.getText() + "'";
            st = con.createStatement();
            int SA = st.executeUpdate(hapus);
            JOptionPane.showMessageDialog(null, "Delete Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Delete Gagal");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        hapuslayar();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardUser(null, true).setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pendaftaran dialog = new Pendaftaran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void
                            windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);

                    }

                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cboAgama;
    private javax.swing.JComboBox<String> cboGolDar;
    private javax.swing.JComboBox<String> cboJK;
    private javax.swing.JComboBox<String> cboKewarganegaraan;
    private javax.swing.JComboBox<String> cboTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAnakKe;
    private javax.swing.JTextField txtAyah;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIbu;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPO;
    private javax.swing.JTextField txtPTO;
    private javax.swing.JTextField txtTTL;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
