package program;

import program.FormRaport;
import program.DashboardUser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ndaru Pratiwi
 */
public class Raport extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;

    /**
     * Creates new form Raport
     */
    public Raport(java.awt.Frame parent, boolean modal) {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost/raport", "root", "");
            st = con.createStatement();

        } catch (Exception ex) {

        }
    }

    private void HapusLayar() {
        txtNamaSiswa.setText("");
        txtInduk.setText("");
        txtKelas.setText("");
        txtGol.setText("");
        txtNamaSiswa.setEnabled(true);
        txtInduk.setEnabled(true);
        txtKelas.setEnabled(true);
        txtGol.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRaport = new javax.swing.JButton();
        txtNamaSiswa = new javax.swing.JTextField();
        txtInduk = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtGol = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Siswa : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 120, 113, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("RAPORT ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 40, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nomor Induk :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 170, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Kelas :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 220, 80, 30);

        btnRaport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRaport.setText("Raport");
        btnRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaportActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaport);
        btnRaport.setBounds(330, 330, 110, 30);
        jPanel1.add(txtNamaSiswa);
        txtNamaSiswa.setBounds(310, 120, 220, 30);
        jPanel1.add(txtInduk);
        txtInduk.setBounds(310, 170, 220, 30);
        jPanel1.add(txtKelas);
        txtKelas.setBounds(310, 220, 220, 30);

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(450, 330, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Golongan :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 270, 100, 30);
        jPanel1.add(txtGol);
        txtGol.setBounds(310, 270, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/C.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 655, 481);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaportActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNamaSiswa.getText().equals("") || txtInduk.getText().equals("") || txtKelas.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                txtNamaSiswa.requestFocus();
                HapusLayar();
            } else {
                st = con.createStatement();
                String sql = ("SELECT * FROM raport WHERE NamaSiswa  ='" + txtNamaSiswa.getText() + "'AND NomorInduk ='" + txtInduk.getText() + "'AND Kelas ='" + txtKelas.getText()+"'AND Golongan ='"+txtGol.getText() + "' ");
                ResultSet rs = st.executeQuery(sql);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
                    HapusLayar();
                    this.setVisible(false);
                    new FormRaport(null, true).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi Gagal \nData yang di inputkan salah", "Pesan", JOptionPane.ERROR_MESSAGE);
                    HapusLayar();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnRaportActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardUser(null, true).setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Raport dialog = new Raport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void
                            windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);

                    }

                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRaport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtGol;
    private javax.swing.JTextField txtInduk;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNamaSiswa;
    // End of variables declaration//GEN-END:variables
}
